### ISSUE TITLE
No download

### ISSUE THREAD

**Issue by woodstock310** [WAZAAAAA0/antimicro#2]
I used antimirco before for working with SolidWorks. Thank you! It save my hand a lot of pain. 
My computer hard drive died on me and I don't have an image of it with your software on it. I tried to download it again but the link to download leads to a dead page.
I am not afraid to use a command line or whatever to down load it but I would have to be told how. I only enough to get me into trouble, not enough to get me out of it yet. :)
Thanks.

**Comment by WAZAAAAA0** [comment]
The main repository has been removed, but you are in the right place, because I backed up all the latest binaries here in this repository!
https://github.com/WAZAAAAA0/antimicro/releases

New maintained repo: https://github.com/AntiMicro/antimicro

**Comment by woodstock310** [comment]
Thank you! I figured it out and got to using it again!

On Wednesday, June 1, 2016, WAZAAAAA notifications@github.com wrote:

> Closed #2 https://github.com/WAZAAAAA0/antimicro/issues/2.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/WAZAAAAA0/antimicro/issues/2#event-679046314, or mute
> the thread
> https://github.com/notifications/unsubscribe/AQ6Fk79cm11btkO1oWoA1x2O9G_5E7uRks5qHfo4gaJpZM4IPI8q
> .

## 

Jason R. Stockton
530-966-2748

Mars or Bust!
