### ISSUE TITLE
Differentiate hold and click?

### ISSUE THREAD

**Issue by surashu** [WAZAAAAA0/antimicro#3]
Hi! Since the main repository has been removed, I'll ask here instead. Do you know of a way to do the following:
- Pressing the Guide button on the controller should open up the Steam overlay.
- Holding the Guide button + pressing the Right Bumper should do a screenshot.

I can't figure out how to mix a single click and a hold to make this work. Any help would be appreciated.

**Comment by WAZAAAAA0** [comment]
Please move any discussion to the actually maintained repository: https://github.com/AntiMicro/antimicro

**Comment by surashu** [comment]
Yeah I posted this before the official consensus to move to an official organization+repo. :PP
